### ISSUE TITLE
Please add a test account 

### ISSUE THREAD

**Issue by liaz-af** [Bshara23/skill-based#1]
This is how we will test the app. 
Thanks and good luck :)

**Comment by Bshara23** [comment]
Hi, thanks for letting me know
I have just confirmed an account with the email: "example@test.com"

if you want to try with a real email you can,
any other valid email would get a verification message via AWS mailing services.

I will add a list of test accounts soon 👍

**Comment by Bshara23** [comment]
Test accounts:

   username: test
   password: Abc1234%

   username: test2
   password: Abc1234%

   username: test3
   password: Abc1234%

I will add them to the README too.
